# Generated by Django 4.2.14 on 2024-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptToImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=10000)),
                ('meta_data', models.JSONField(blank=True, default=None)),
                ('image_output', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
