# Generated by Django 4.2.14 on 2024-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttoimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttoimage',
            name='meta_data',
            field=models.JSONField(blank=True),
        ),
    ]
