# Generated by Django 4.2.14 on 2024-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttoimage', '0002_alter_prompttoimage_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttoimage',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
